In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import yfinance as yf

In [4]:
tech_layoffs = pd.read_csv(r"C:\Users\Nahye\OneDrive - University of Toronto\Documents\Project\Tech Layoff 2\PowerBI Final Data.csv")
tech_layoffs

,#,% Laid Off,Company,Company Size After,Company Size Before,Continent,Country,Year,Quarter,Month,Day,Funding Stage,Funding Stage Grouped,Industry,Laid Off,Location HQ,Money Raised in Mill,Sector,Year.1
0,1,40.0,Tamara Mellon,30.0,50.0,North America,USA,2020,Qtr 1,March,12,Series C,Growth Stage,Retail,20.0,Los Angeles,90.0,Consumer & Retail,2020
1,2,10.0,HopSkipDrive,72.0,80.0,North America,USA,2020,Qtr 1,March,13,Unknown,Unknown,Transportation,8.0,Los Angeles,45.0,Travel and Transportation,2020
2,3,75.0,Panda Squad,2.0,8.0,North America,USA,2020,Qtr 1,March,13,Seed,Early Stage,Consumer,6.0,San Francisco,1.0,Consumer & Retail,2020
3,4,100.0,Help.com,0.0,16.0,North America,USA,2020,Qtr 1,March,16,Seed,Early Stage,Support,16.0,Austin,6.0,Professional Services,2020
4,5,22.0,Inspirato,461.0,591.0,North America,USA,2020,Qtr 1,March,16,Series C,Growth Stage,Travel,130.0,Denver,79.0,Travel and Transportation,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767,1835,NaN,Moxion Power,NaN,NaN,North America,USA,2024,Qtr 2,June,26,Unknown,Unknown,Energy,101.0,Richmond,124.0,Energy & Utilities,2024
1768,1836,5.0,Perion,665.0,700.0,Asia,Israel,2024,Qtr 2,June,26,Post-IPO,Maturity or Exit,Marketing,35.0,Tel Aviv,76.0,Professional Services,2024
1769,1837,17.0,Planet,879.0,1059.0,North America,USA,2024,Qtr 2,June,26,Post-IPO,Maturity or Exit,Aerospace,180.0,San Francisco,574.0,Manufacture and Infrasturcture,2024
1770,1838,4.0,RealPage,480.0,500.0,North America,USA,2024,Qtr 2,June,27,Acquired,Maturity or Exit,Real Estate,20.0,Dallas,105.0,Real Estate,2024
1771,1839,17.0,Priceline,503.0,606.0,North America,USA,2024,Qtr 2,June,28,Acquired,Maturity or Exit,Travel,103.0,Norwalk,77.0,Travel and Transportation,2024

In [5]:
tickers = ['AMZN', 'MSFT', 'META', 'JNJ', 'BRK-B', 'INTU']
start_date = "2020-01-01"
end_date = "2025-01-11"

stock_data_list = []

In [6]:
for ticker in tickers:
    print(f"Downloading data for {ticker}...")
    data = yf.download(ticker, start=start_date, end=end_date)
    stock_data_list.append(data)
    file_name = f"{ticker}_stock.csv"
    data.to_csv(file_name)
    print(f"Stock data saved as {file_name}")

Downloading data for AMZN...

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Stock data saved as AMZN_stock.csv
Downloading data for MSFT...
Stock data saved as MSFT_stock.csv
Downloading data for META...

[*********************100%***********************]  1 of 1 completed

Stock data saved as META_stock.csv
Downloading data for JNJ...

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Stock data saved as JNJ_stock.csv
Downloading data for BRK-B...
Stock data saved as BRK-B_stock.csv
Downloading data for INTU...

[*********************100%***********************]  1 of 1 completed

Stock data saved as INTU_stock.csv